local wezterm = require 'wezterm';
return {
  font     	= wezterm.font("JetBrainsMono NF"),
  font_size	= 9.0,
  color_scheme     	= "GruvboxDark",
  colors           	= {
   foreground     	= "#ebdbb2",
   background     	= "#1a1a1a",
   cursor_bg      	= "#a89984",
   cursor_fg      	= "#282828",
   cursor_border  	= "#a89984",
   selection_fg   	= "#282828",
   selection_bg   	= "#fffacd",
   scrollbar_thumb	= "#282828",
   split          	= "#32302f",
  },
  window_background_opacity   	= 0.90,
  enable_tab_bar              	= true,
  hide_tab_bar_if_only_one_tab	= true,
  keys = {
   { key = "h", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Left"}},
   { key = "j", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Down"}},
   { key = "k", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Up"}},
   { key = "l", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Right"}},
   { key = "H", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Left", 5}}},
   { key = "J", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Down", 5}}},
   { key = "K", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Up", 5}}},
   { key = "L", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Right", 5}}},
   { key = "1", mods = "LEADER",       action=wezterm.action{ActivateTab=0}},
   { key = "2", mods = "LEADER",       action=wezterm.action{ActivateTab=1}},
   { key = "3", mods = "LEADER",       action=wezterm.action{ActivateTab=2}},
   { key = "4", mods = "LEADER",       action=wezterm.action{ActivateTab=3}},
   { key = "5", mods = "LEADER",       action=wezterm.action{ActivateTab=4}},
   { key = "6", mods = "LEADER",       action=wezterm.action{ActivateTab=5}},
   { key = "7", mods = "LEADER",       action=wezterm.action{ActivateTab=6}},
   { key = "8", mods = "LEADER",       action=wezterm.action{ActivateTab=7}},
   { key = "9", mods = "LEADER",       action=wezterm.action{ActivateTab=8}},
   { key = "x", mods = "LEADER",       action=wezterm.action{CloseCurrentPane={confirm=true}}},
   { key ="v",  mods = "SHIFT|CTRL",    action=wezterm.action.PasteFrom 'Clipboard'},
   { key ="c",  mods = "SHIFT|CTRL",    action=wezterm.action.CopyTo 'Clipboard'},
   { key = "+", mods = "SHIFT|CTRL",   action="IncreaseFontSize" },
   { key = "-", mods = "SHIFT|CTRL",   action="DecreaseFontSize" },
   { key = "0", mods = "SHIFT|CTRL",   action="ResetFontSize" },
  },
  set_environment_variables = {},
  adjust_window_size_when_changing_font_size = false,
  window_decorations = "RESIZE",
  initial_rows = 55,
  initial_cols = 220,
}
